apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ke8pgkje7-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:ce97a48cfcdd0628cf19f8665f0ad2f70b8a395f@sha256:97fb07386f6975d453d32d0df64c94d987a92b566a683f0f1b2561c740f80b4e
          name: container-image
